(function() {
    let macros = {
        "\\Σ": "\\sum",
        "∄": "\\nexists",
        "·": "\\cdot",
        "⊲": "\\lhd",
        "⊥": "\\perp",
        "∥": "\\parallel",
        "∖": "\\setminus",
        "ø": "\\varnothing",
        "𝓔": "\\mathcal{E}",
        "\\o": "\\varnothing",
        "\\Rg": "\\operatorname{Rg}",
        "\\tr": "\\operatorname{tr}",
        "\\arg": "\\operatorname{arg}",
        "\\Arg": "\\operatorname{Arg}",
        "\\ord": "\\operatorname{ord}",
        "\\sgn": "\\operatorname{sgn}",
        "\\pr": "\\operatorname{пр}",
        "\\Ker": "\\operatorname{Ker}",
        "\\Im": "\\operatorname{Im}",
        "\\id": "\\operatorname{id}",
        "\\Char": "\\operatorname{char}",
        "\\const": "\\operatorname{const}",
        "\\Va": "\\vec{a}",
        "\\Vb": "\\vec{b}",
        "\\Vc": "\\vec{c}",
        "\\Ve": "\\vec{e}",
        "\\Vo": "\\vec{0}",
        "\\Vi": "\\vec{i}",
        "\\Vj": "\\vec{j}",
        "\\Vk": "\\vec{k}",
        "\\Vn": "\\vec{n}",
        "\\Vs": "\\vec{s}",
        "\\bar": "\\overline",
        "\\tilde": "\\widetilde",
        "\\codir": "\\uparrow\\uparrow",
        "\\difdir": "\\uparrow\\downarrow",
    };
    
})()
